name: VersionTool
author: "HydrolienF"
description: 'Versioning based on branch name and commit count of your repository.'
branding:
  icon: 'chevron-up'
  color: 'orange'

outputs:
  version:
    description: "version string"
    value: ${{ steps.version.outputs.version }}

runs:
  using: "composite"
  steps:

  - name: updateVersion
    id: startBranchName
    shell: bash
    run: |
      export PATH_TO_SH=${{ github.action_path }}
      startBranchName=$(git rev-parse --abbrev-ref HEAD)
      echo "-------------"
      echo $startBranchName
      echo "-------------"
      echo "startBranchName=$startBranchName" >> $GITHUB_OUTPUT

  - name: ini git
    shell: bash
    run: |
      export PATH_TO_SH=${{ github.action_path }}
      echo "-------------"
      ls
      echo "-------------"
      git fetch
      echo "-------------"
      lastBranch=$($PATH_TO_SH/getLastGitBranch.sh)
      echo $lastBranch | cat -v
      echo "-------------"
      git switch $lastBranch -f
      git pull
      echo "-------------"

  - name: updateVersion.sh
    id: version
    shell: bash
    run: |
      export PATH_TO_SH=${{ github.action_path }}
      version=$($PATH_TO_SH/updateVersion.sh)
      echo "-------------"
      echo $version
      echo "-------------"
      echo "version=$version" >> $GITHUB_OUTPUT

  - name: clean git ref
    shell: bash
    run: |
      git switch ${{ steps.startBranchName.outputs.startBranchName }}
