name: Version-Tool
author: "HydrolienF"
description: 'Versioning based on branch name and commit count of your repository.'

on:
  pull_request:
    branches: [ master ]

jobs:
  updateVersionJob:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: chmod
      run: |
        chmod 700 *.sh
    - name: ini git
      run: |
        echo "-------------"
        git fetch
        echo "-------------"
        lastBranch=$(./getLastGitBranch.sh)
        echo $lastBranch | cat -v
        echo "-------------"
        git switch $lastBranch
        echo "-------------"
    - name: updateVersion.sh
      run: ./updateVersion.sh
    - name: commit version.md
      run: |
        if [[ `git status --untracked-files=no --porcelain docs/` != "\n" ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.md
          git commit -m "Auto version.md update"
          git push
        fi
