name: Version-Tool
author: "HydrolienF"
description: 'Versioning based on branch name and commit count of your repository.'
branding:
  icon: 'chevron-up'
  color: 'orange'

runs:
  using: "composite"
  steps:
  # - name: checkout
  #   uses: actions/checkout@v2
  - id: chmod
    shell: bash
    run: |
      chmod 700 *.sh

  - id: ini git
    shell: bash
    run: |
      echo "-------------"
      git fetch
      echo "-------------"
      lastBranch=$(./getLastGitBranch.sh)
      echo $lastBranch | cat -v
      echo "-------------"
      git switch $lastBranch
      echo "-------------"

  - id: updateVersion.sh
    shell: bash
    run: ./updateVersion.sh
  - id: commit version.md
    shell: bash
    run: |
      if [[ `git status --untracked-files=no --porcelain docs/` != "\n" ]]; then
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add version.md
        git commit -m "Auto version.md update"
        git push
      fi
