name: VersionTool
author: "HydrolienF"
description: 'Versioning based on branch name and commit count of your repository.'
branding:
  icon: 'chevron-up'
  color: 'orange'

outputs:
  version:
    description: "version string"
    value: ${{ steps.version.outputs.version }}

runs:
  using: "composite"
  steps:

  # - name: chmod
  #   shell: bash
  #   run: echo "test"

  - name: chmod
    shell: bash
    run: chmod 700 *.sh

  - name: updateVersion.sh
    id: startBranchName
    shell: bash
    run: |
      startBranchName=$(git rev-parse --abbrev-ref HEAD)
      echo "-------------"
      echo $startBranchName
      echo "-------------"
      echo "::set-output name=startBranchName::$startBranchName"

  - name: ini git
    shell: bash
    run: |
      echo "-------------"
      ls
      echo "-------------"
      # TODO download *.sh from Version-Tool repository
      echo "-------------"
      ls
      echo "-------------"
      git fetch
      echo "-------------"
      lastBranch=$(./getLastGitBranch.sh)
      echo $lastBranch | cat -v
      echo "-------------"
      git switch $lastBranch -f
      git pull
      echo "-------------"

  - name: updateVersion.sh
    id: version
    shell: bash
    run: |
      version=$(./updateVersion.sh)
      echo "-------------"
      echo $version
      echo "-------------"
      echo "::set-output name=version::$version"

  - name: clean git ref
    shell: bash
    run: |
      git switch ${{ steps.startBranchName.outputs.startBranchName }}
