name: Version-Tool
author: "HydrolienF"
description: 'Versioning based on branch name and commit count of your repository.'
branding:
  icon: 'chevron-up'
  color: 'orange'

outputs:
  version:
    description: "version string"
    value: ${{ steps.version.outputs.version }}

runs:
  using: "composite"
  steps:

  - name: chmod
    shell: bash
    run: chmod 700 *.sh

  - name: ini git
    shell: bash
    run: |
      echo "-------------"
      git fetch
      echo "-------------"
      lastBranch=$(./getLastGitBranch.sh)
      echo $lastBranch | cat -v
      echo "-------------"
      git switch $lastBranch
      echo "-------------"

  - name: updateVersion.sh
    id: version
    shell: bash
    run: |
      version=$(./updateVersion.sh)
      echo "::set-output name=version::$version"
